### ISSUE TITLE
ICO Task list

### ISSUE THREAD

**Issue by isysd** [isysd/isysd.github.io#1]
+ [ ] Polish website copy so it is descriptive, funny, and ICOy
 + [ ] redesign profile picture section so it is flashier, with "decentralized" or "blockchain" background imagery
 + [ ] Change <pre><code> styles so they stand out more
 + [ ] Add countdown timer, money counter and other fancy ICO widgets
 + [ ] Add "Buy now" page
 + [ ] Update home page to include "Buy now" instructions
 + [ ] Video script
 + [ ] Film Video
 + [ ] Video editing & Publishing
 + [ ] Prep friends & family, with hashtag #BirthdayICO
 + [ ] Everyone share and hashtag on the 23rd
